# Generated by Django 2.0.6 on 2019-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('ip', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tiem', models.CharField(max_length=50)),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'investment',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('amount', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('cus_type', models.CharField(max_length=10)),
                ('time_period', models.CharField(max_length=10)),
                ('time_limit', models.IntegerField()),
                ('instotution', models.CharField(max_length=50)),
                ('payment', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('work_time', models.IntegerField()),
                ('salary_after_tax', models.FloatField()),
                ('purpose', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'money',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('y_rate', models.FloatField()),
                ('time_limit', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('phone', models.IntegerField()),
                ('passwd', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('identity', models.IntegerField()),
                ('bank_num', models.IntegerField()),
                ('banks', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('open_bank', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('edu', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=30)),
                ('marriage', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('home', models.BooleanField()),
                ('car', models.BooleanField()),
                ('em_contact', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
