# Generated by Django 2.2.1 on 2019-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='tiem',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='industry',
            name='ip',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
